name: Infra Deployment and Training

on:
  push:
    paths: 
      - '.github/workflows/setup.yml'
 
env:
  AZURE_RESOURCE_GROUP: sai-rg 
  STORAGE_ACCOUNT: githubmlopstest
      
jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2
    
    - name: Azure Login
      id: azure_login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Azure resources
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az deployment group create \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --template-file $GITHUB_WORKSPACE/infra/deploy.core-infra.json \
            --parameters $GITHUB_WORKSPACE/infra/params.deploy.core-infra.json \
            patToken=${{secrets.PATTOKEN}} repo_name=$GITHUB_REPOSITORY DataLakestorageName=${{ env.STORAGE_ACCOUNT }}
